#define INTEGER 1
#define ARRAY 2

#define OPERATOR 3

#define IDENTIFIER 4
#define IF 5
#define ELSE 6
#define WHILE 7
#define DO 8
#define RETURN 9
#define MAINFUNCTION 10


#define SEPERATOR 11
#define SEMICOLON 12
#define WITHESPACE 13
#define OPENBRACKET 14
#define CLOSEBRACKET 15
#define OPENPATENTHESE 16
#define CLOSEPATENTHESE 17

#define FUNCTION_DEFINITION 18
#define FUNCTION_CALL 19
#define PRINT_FUNCTION 20
#define READ_FUNCTION 21
#define TYPE 22

#define NEXTLINE 23